// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxnK4FiZVFz3kgsBJw0xYwtfHtmygDT_8',
    appId: '1:1039193400778:web:02ab631619cef7a5fa5b33',
    messagingSenderId: '1039193400778',
    projectId: 'pyramakerz-attendance',
    authDomain: 'pyramakerz-attendance.firebaseapp.com',
    storageBucket: 'pyramakerz-attendance.appspot.com',
    measurementId: 'G-QC07LWPR65',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsHt4BrrdDa-ruHhjwnklnR2EQ0vDXaxI',
    appId: '1:1039193400778:android:2597dc17a23c34b4fa5b33',
    messagingSenderId: '1039193400778',
    projectId: 'pyramakerz-attendance',
    storageBucket: 'pyramakerz-attendance.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZU_3CjD0gUY86whBZMm0_mkvtxVRuD1c',
    appId: '1:1039193400778:ios:c24bbc9a63019d1dfa5b33',
    messagingSenderId: '1039193400778',
    projectId: 'pyramakerz-attendance',
    storageBucket: 'pyramakerz-attendance.appspot.com',
    iosBundleId: 'com.example.hrProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZU_3CjD0gUY86whBZMm0_mkvtxVRuD1c',
    appId: '1:1039193400778:ios:c35b1163fcbe30d6fa5b33',
    messagingSenderId: '1039193400778',
    projectId: 'pyramakerz-attendance',
    storageBucket: 'pyramakerz-attendance.appspot.com',
    iosBundleId: 'com.example.pyramakerzAtendnace.RunnerTests',
  );
}
